---
# tasks file for roles/common
- name: Ping all Servers
  hosts: all
  tasks:
    - name: Ping all servers to check connectivity
      ansible.builtin.ping:

- name: Installing docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        name: docker.io
        state: present 

- name: Installing docker compose
sudo usermod -aG docker $USER


- name: Logging in docker