
- name: Docker in back
  hosts: app
  become: true
  vars_files:
    - vars.yml
    - secrets.yml      
  tasks:
    - name: Copying compose file 
      ansible.builtin.template:
        src: compose/docker-compose.back.yml.j2
        dest: /home/ubuntu/docker-compose.back.yml
        owner: ubuntu 
        group: ubuntu
        mode: '0644'

    - name: Composing containers in back
      command: docker compose -f docker-compose.back.yml up -d 