---

- name: Docker in front
  hosts: frontend
  become: true
  vars_files:
    - compose/vars.yml
    - secrets.yml    
    
  tasks:
    - name: Copying compose file 
      ansible.builtin.template: 
        src: compose/docker-compose.front.yml.j2
        dest: /home/ubuntu/docker-compose.front.yml
        owner: ubuntu 
        group: ubuntu
        mode: '0644'

    - name: Composing containers in front
      command: docker compose -f docker-compose.front.yml up -d 
