- name: Ping all Servers
  hosts: all
  tasks:
    - name: Ping all servers to check connectivity
      ansible.builtin.ping:

- name: Update apt package index
  hosts: all
  tasks:
    - name: installing docker
      ansible.builtin.apt:
        update_cache: yes

- name: Installing docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        name: docker.io
        state: present 